services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
    - key: APP_KEY
      value: base64:aCugHaSOnsFDB8SAWwlVoN0i4oL7voZGBe/KHV0pEG0=
    - key: APP_ENV
      value: production
    - key: APP_DEBUG
      value: false
    - key: DB_CONNECTION
      value: sqlite
    - key: DB_DATABASE
      value: /var/www/database/database.sqlite


